# Generated by Django 5.2.5 on 2025-08-10 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('opsd', 'Open Power System Data'), ('entsoe', 'ENTSO-E Transparency'), ('manual', 'Manual Upload')], max_length=20)),
                ('import_timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_start_date', models.DateTimeField()),
                ('data_end_date', models.DateTimeField()),
                ('records_imported', models.PositiveIntegerField(default=0)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_log', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_timestamp', models.DateTimeField(db_index=True)),
                ('cet_cest_timestamp', models.DateTimeField(db_index=True)),
                ('country_code', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_ahead_price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('bidding_zone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'unique_together': {('country_code', 'utc_timestamp')},
            },
        ),
        migrations.CreateModel(
            name='LoadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_timestamp', models.DateTimeField(db_index=True)),
                ('cet_cest_timestamp', models.DateTimeField(db_index=True)),
                ('country_code', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_load_mw', models.FloatField(blank=True, help_text='Total actual load in MW', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('forecast_load_mw', models.FloatField(blank=True, help_text='Day-ahead load forecast in MW', null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Load Data',
                'verbose_name_plural': 'Load Data',
                'unique_together': {('country_code', 'utc_timestamp')},
            },
        ),
        migrations.CreateModel(
            name='RenewableGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_timestamp', models.DateTimeField(db_index=True)),
                ('cet_cest_timestamp', models.DateTimeField(db_index=True)),
                ('country_code', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_type', models.CharField(choices=[('solar', 'Solar'), ('wind_onshore', 'Wind Onshore'), ('wind_offshore', 'Wind Offshore'), ('wind_total', 'Wind Total')], max_length=20)),
                ('actual_generation_mw', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity_mw', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity_factor', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'unique_together': {('country_code', 'utc_timestamp', 'generation_type')},
            },
        ),
    ]
