# Generated by Django 5.2.5 on 2025-08-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('location', models.CharField(max_length=100)),
                ('country_code', models.CharField(db_index=True, max_length=10)),
                ('temperature_celsius', models.FloatField(blank=True, null=True)),
                ('temperature_min_celsius', models.FloatField(blank=True, null=True)),
                ('temperature_max_celsius', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('wind_direction_degrees', models.FloatField(blank=True, null=True)),
                ('cloud_cover_percent', models.FloatField(blank=True, null=True)),
                ('precipitation_mm', models.FloatField(blank=True, null=True)),
                ('solar_irradiance_wm2', models.FloatField(blank=True, null=True)),
                ('pressure_hpa', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['country_code', 'timestamp'], name='weather_wea_country_79aa9b_idx')],
                'unique_together': {('country_code', 'location', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_timestamp', models.DateTimeField()),
                ('target_timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('temperature_celsius', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('cloud_cover_percent', models.FloatField(blank=True, null=True)),
                ('solar_irradiance_wm2', models.FloatField(blank=True, null=True)),
                ('forecast_horizon_hours', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('country_code', 'location', 'target_timestamp', 'forecast_horizon_hours')},
            },
        ),
    ]
