# Generated by Django 5.2.5 on 2025-08-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='radiation_diffuse_wm2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='radiation_direct_wm2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
